-- WINDOW FUNCTIONS
CREATE TABLE A(
    AID INT,
    VALUE VARCHAR(10)
);
CREATE TABLE B(
    BID INT,
    VALUE VARCHAR(10)
);
CREATE TABLE C(
    CID INT,
    VALUE VARCHAR(10)
);
INSERT INTO A (AID, VALUE) VALUES 
(1, 'A1'), (2, 'A2'), (3, 'A3'), (5, 'A5'), (1, 'X1'), (2, 'X2'),
(2, 'X3'), (3, 'X4'), (4, 'X5'), (4, 'X6'), (6, 'X7'), (7, 'X8'),
(7, 'X9');
INSERT INTO B (BID, VALUE) VALUES 
(2, 'B2'), (3, 'B3'), (4, 'B4'), (6, 'B6'), (2, 'Y1'), (3, 'Y2'),
(3, 'Y3'), (5, 'Y4'), (7, 'Y5'), (8, 'Y6'), (8, 'Y7'), (9, 'Y8');
INSERT INTO C (CID, VALUE) VALUES 
(3, 'C3'), (4, 'C4'), (7, 'C7'), (3, 'Z1'), (3, 'Z2'), (4, 'Z3'),
(5, 'Z4'), (5, 'Z5'), (6, 'Z6'), (8, 'Z7'), (9, 'Z8'), (9, 'Z9');

-- OVER
SELECT *, 
SUM(AID) OVER(ORDER BY AID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_SUM
FROM A;

-- ROW NUMBER
SELECT *, 
ROW_NUMBER() OVER(PARTITION BY AID ORDER BY VALUE) AS ROW_NUMBER
FROM A;

-- RANK
SELECT *, 
RANK() OVER(ORDER BY AID) AS AID_RANK
FROM A;

-- DENSE RANK
SELECT *, 
DENSE_RANK() OVER(ORDER BY AID) AS AID_DENSE_RANK
FROM A;

-- LEAD
SELECT *,
LEAD(VALUE, 1) OVER(ORDER BY AID) AS LEAD_ROW_VALUE
FROM A;

-- LAG
SELECT *,
LAG(VALUE, 1) OVER(ORDER BY AID) AS LEAD_ROW_VALUE
FROM A;
